efault: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  pool: 15

development:
  <<: *default
  database: iris_fe_development

test:
  <<: *default
  database: iris_fe_test

production:
  <<: *default
  database: iris_fe_production
  username: iris_fe
  password: <%= ENV['IRIS_FE_DATABASE_PASSWORD'] %>
